model:
  arch: mini_gpt4

  # vit encoder
  freeze_vit: True
  vit_path: "/path/to/InternVideo-MM-L-14.ckpt"

  # Q-Former
  num_query_token: 32

  # Vicuna
  llama_model: "/path/to/vicuna-13b-delta-v0/out"

  # generation configs
  prompt: ""

preprocess:
    vis_processor:
        train:
          name: "blip2_image_train"
          image_size: 224
        eval:
          name: "blip2_image_eval"
          image_size: 224
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"
